### ISSUE TITLE
errors with the playlist feauture

### ISSUE THREAD

**Issue by Jirido** [themayankjha/JAKYM#15]
Hi I have installed JAKYM with yay from AUR on a arch64 machine.
While trying to play a playlist this happens:
 jakym -y https://www.youtube.com/playlist?list=PLz4zPQvMRasSJ6c6HXjm3qRSs2shSlqHg
                                                - by Lex
Pinging Youtube
Processing Song: 1/5
Traceback (most recent call last):
  File "/home/jirido/.local/bin/jakym", line 8, in <module>
    sys.exit(main())
  File "/home/jirido/.local/lib/python3.9/site-packages/jakym/__main__.py", line 190, in main
    playyoutube(args.y)
  File "/home/jirido/.local/lib/python3.9/site-packages/jakym/__main__.py", line 25, in playyoutube
    tempytplaylist,beg=downloader.ytplaylistparser(link,beg)
  File "/home/jirido/.local/lib/python3.9/site-packages/jakym/downloader.py", line 56, in ytplaylistparser
    for song in meta['entries']:
UnboundLocalError: local variable 'meta' referenced before assignment

If I try from within almost the same happens.
–––––––––––––––––––––––––––––––––––––
						- by Lex
youtube
Enter Playlist: https://www.youtube.com/playlist?list=PLz4zPQvMRasSJ6c6HXjm3qRSs2shSlqHg
Pinging Youtube
Processing Song: 1/5
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jirido/.local/lib/python3.9/site-packages/jakym/__main__.py", line 136, in queue
    playyoutube(ytplaylist)
  File "/home/jirido/.local/lib/python3.9/site-packages/jakym/__main__.py", line 25, in playyoutube
    tempytplaylist,beg=downloader.ytplaylistparser(link,beg)
  File "/home/jirido/.local/lib/python3.9/site-packages/jakym/downloader.py", line 56, in ytplaylistparser
    for song in meta['entries']:
UnboundLocalError: local variable 'meta' referenced before assignment
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jirido/.local/lib/python3.9/site-packages/jakym/__main__.py", line 136, in queue
    playyoutube(ytplaylist)
  File "/home/jirido/.local/lib/python3.9/site-packages/jakym/__main__.py", line 25, in playyoutube
    tempytplaylist,beg=downloader.ytplaylistparser(link,beg)
  File "/home/jirido/.local/lib/python3.9/site-packages/jakym/downloader.py", line 56, in ytplaylistparser
    for song in meta['entries']:
UnboundLocalError: local variable 'meta' referenced before assignment

Something strange also happens when trying to find a song.
$ jakym
bumblebee
Downloading bumblebee song
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests

then it succeeds.
---------------------------------------
If i try to play one song it works but maybe related to the playlist problem it also tells me:
						- by Lex
https://www.youtube.com/watch?v=TJ8ws2dqqFg
Downloading https://www.youtube.com/watch?v=TJ8ws2dqqFg song
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests

And if I search for a song 
						- by Lex
hooker
Downloading hooker song
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Error downloading hooker song

but then it manages anyway..
Done Downloading
Currently Playing : Lex and jack (music video
Do I do something wrong or am I missing some dependency?

**Comment by themayankjha** [comment]
Hey @Jirido 
Thank you for your Issue!
I tried to replicate your errors but was unsuccessful. Maybe it is due to my package being installed via the instructions in the README. I'll try using an arch system and will update you on the same :)

**Comment by themayankjha** [comment]
Hey!
After some testing I am unable to reproduce any of the bugs. 
From what i understand the warning is probably ytdl freaking youtube out with multiple requests. Are you using a VPN?

I am successfully able to play the same playlist that you mention in the issue without any hitch
![Screenshot_20211130_001226](https://user-images.githubusercontent.com/34495260/143924618-9957619d-d719-4774-b916-ee9f5fa3aec3.png)

I cleaned installed manjaro minimal xfce and used yay to get the AUR package.
Can you share anything more to pinpoint the issue?
